[project]
name = "alert-operator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.20.0.post0",
    "kubernetes>=32.0.1",
    "redis>=5.2.1",
]
